JOKE_STRINGS = (
    "If you cry on seeing the question paper it is an insult😢!\nIf your teacher cries on seeing your answer paper,it is your achievement😂!",
    "Lorry’la karumbu yethina Kaasu...\nKarumbula Lorrya Yethina Juiceuh...\nIthelam oru msg’nu padikkiravan oru *😂😂",
    "Pirappu oru murai😭\nirappu oru murai😢😢\nvazhkai oru murai🥲\nbut sappadu mattum daily 3 murai😂🤣\nnamaku soruthan mukkiyam🤣🤣",
    "Sir: yenda home work pannala😡?\nBoy: current illa sir🥲.\nSir: handle use panna vendiyathu thane😒!\nBoy: theeppetti illa sir😞.\nSir: yenda illa🤨?\nBoy:irunthuchi samy roomla irunthuchi😌.\nSir:yenda edukkala🤬?\nBoy: kulikkala sir🥴.\nSir: yenda kulikkala😬?\nBoy: motor work akala sir🥶.\nSir: yenda work akala🤥?\nBoy: yethana vatti solrathu current illa sir🤥🥱😂!",
    "Patient:doctor theriyaama sim card mulunkitten🤢\nDoctor:velia edukka 100 rupa aagum😕\nPatient:appa vendam ,athula 10 rupathaan balence irukku🥴\nDoctor:🙄🙄",
    "96 girl friends\n59 figures\n67 lovers\n96 kisses\n00 marks\nThis is my life style😍!\nAppadinu soanna nambva poringa eathu enn mobile number pa 😂😂",
    "In a shop\ngirl:How much this dress costs🤔?...\nNaughty Salesboy : Just 25 kisses💋💋...\nGirl: ok, pack the dress😁...My grandma will pay the bill... Ha! ha! ha! ha😂😂😂!\nNaughty Salesboy:😳😳No need . You take this dress for free😳",
    "On the road...\nLady : stupid, idiot.. Ivlo vegama bike’la variye...yen mela mothi irundha enna aayirukkum.😡!\nBoy : Nee ivlo pesi irukka matta.😂!",
    "Joke ah 😧😧 ayo marandhute pa 🥱",
    "AMAITHIYANA PONNUM DAINOSARUM ORU VITHATHTHIL ONNUTHAN😏..\nBECAUSE...., RENDUMEA IPPA ULAGATHIL ILLAI🥴",
    "Girl:kamani anbodu my dear uyir'ku naan anupum msg❤️....\nBoy:illa sms.... vena msg'a irukkatum😁.Girl:ponmani uncellil signal kidaikkutha🥴?! en cellil ingu kidaikuthey😅.\nGirl:unnai enni paarkail msg kottuthey🥺....athai anuppa ninaikayil balance muttuthu🥴!\nGirl:manithar purinthu kolla ithu mokka msg alla😌... athayum thandi mattamaanathu🥴🥴🥴.....\nBoy:athu ennamo theriyala, enna maayamo puriyala, un dappa cellukku mattum msg anuppama irukka mudiyala😤😤...",
    "Dhanush:night aana namakku yen thookkam varuthu'nu theriuma😅?\nRaj:Theriyathu\nDhanush:theriyatha😒..........?\nRaj:Ahma😒\nDhanush:Nan sollattuma😂................?\nRaj:Soldra😕\nDhanush:ippo enakku thookkam varuthu, naalaikku solren good night🥱😂😂..........",
    "ennakku neengal thodarnthu sms anuppinal , win pannalam!\n1- 10 laksh mathippulla car'oda photo😂\n2-29 inch color tv'oda attai petti🤣\n3-singapore pogum aeroplanek;ku TATA kaatum vaaipu🥴\n4-MEGA PRIZE - ennudan breakfast / lunch / dinner......athuvum ungal selavil👌..miss pannathinga apparam varutha paduvenga 😞😂😂😂",
    "Sai:PONGALUKKUM DEEPAVAIKKUM ENNA VIDHYAASAM🤔?\n Dhanush:DEEPALIANNIKI PONGAL SAPIDALAAM AANA PONGAL ANNIKI DEEPAVALI SAAPIDAMUDIYUMAA🤣🤣🤣🤣?\nSai:🙄🙄",
    "In an examination hall\nFirst bench students:Dai i will get 90 marks da . Full ah therinja questions❤️❤️\nSecond bench students:Dai 2nd question answer sollu da 🥺\nThird bench students: Etho da na kandipa fail than.\nLast bench students:Dai ethuku da test eluthekitu ☹️ teacher ah paarunga da evalo alaga irukanga nu🥰",
    "Thalapathy vijay: Dai na oru padam nadichiruken la kuruvi nu full form of ku - ru - vi ?\nOne man:KU -KURANGU RU -ROOPATHIL VI- VIJAY😂\nThalapathy vijay:😳😳",
    "Sweetest kiss😍?\n*Head*\nLoveliest kiss❤️?\n*Cheeks*\nMost romantic kiss😘?\n*Lips*\nThe Hottest kiss🥰??\n**Bike Silencer**😂😂😂",
    "Oru nadigar thannode Gold chaina kadichukittae irukkar why☹️?\nYosinga🤨......\nBecause avar NAGAI SUVAI NADIGAR😂",
    "Paal poota paalkaaran. tapaal poota tapaal karan .paper poota paperkaran\naana pichai poota😳😳?",
    "Tea master tea podalam😁\nporata master porata podalam😁\nmaths master maths podalam😁\n Apdina head master mandaya poduvara😳😂",
    "Amma parungaga\nAppa parungga\nAkka parungga\nAnna parungga\nEllarum parungga\nOru kutty kurangu evalo alaga intha message padikuthu nu😂😂",
    "Expectation😌 : \n*Rain🥰 \n*Ilayaraja songs🥰 \n*Tea & bajji🥰\nReality :\n*Motta veyil🥵\n*Powercut 🥴\n*kosukadi🤢",
    "Teacher : Dai varapora examla nee 90 mark edukanum☹️ .\nStudent : 100 mark vanguven sir😍 . \nTeacher : Dai comedy pannatha da 😂\nStudent : First yaaru sir comedy pannathu🤣",
    "Wife : mama , sorgathula husband and wife senthu vala mudiyathamee 😣?/nHusband : athunala thandi athu sorgam .😆",
    "Sivaji movie Rajinikanth : Yean ma enna engineering padika vaicha😒?\nHis mom : Viscom padicha ponnu thara matanga da😣",
    "Wife : Dinner eruka☹️?\nHusband: choice eruka 😕?\nWife : 2 choice eruku😁 .\nHusband: ennana🤔 ? \nWife : venuma ? vendama ?😂",
    "Cricketcoach:Who thought of the One Day INternationals cricket match (ODI)??\n??\n???Who??\nOne boy:Its mahakavi Bharathiaar because he sang ODI vilayadhu paappa\nCricketcoach,🙄🙄",
    "Teacher:What would you call a girl driving a car🤔?\n?\n?\nStudent:A Pen Drive😂\nTeacher:🙄🙄",
    "Santa Banta Tamil Joke\nOne day Santa bought a “kaadhal” film vcd and kept in the fridge🥶; you know why🤔?\nBecause he wanted to see jillunu oru kadhal movie😂",
    "What Is The Diff BTWN Understand & Misunderstand.🤔?\nFriend Figure Aachuna Athu Understand😅!\nFigure Friend Aachuna Athu Misunderstand..🤢!",
    "First man:Mumtaz'in nyabagarthama Shah Jahan Taj Mahal'ai kattinaaru🥺.\nSecond naughty man:Mutta payale🤣, naana irundha ava thangachiyai katti iruppaen😍😂.",
    "Man: Swamiji ulagam en ipdi suthudhu…🥴?\nSwamiji: oru quarter thanni adichaa manushanae suthum boadhu,3 quarter thanni irukura ulagam en sutha koodadhu🥱😂?",
    "Girl: Darling😊. . . Veettoda Maapilaiya Irupingalaa'nu dad Kekraar...😢?\nBoy: Unga Appa Kaaga Illanaalum Un Thangachikaaga Irukken'da Chellam🥰🥰😂\nGirl:🙄😡",
    "டீகப்பில் டீ இருக்கும்😁\nகாபி கப்பில் காபி இருக்கும்😁 \nசூப் கப்பில் சூப் இருக்கும்😁 \nWord கப்பில் Word இருக்குமா😳!",
    "சிக்கன் பிரியாணியில் சிக்கன் இருக்கும் இடியாப்பத்தில் இடி இருக்குமா😳😂?!\nIthelam oru joke nu padikira unakku brain irukuma😂😂 ??",
    "தண்ணீருக்குள் கப்பல் போனா உல்லாசம்🤷,\nகப்பலுக்குள் தண்ணீர் போனா கைலாசம்😂!",
    "வெயிலுக்கும் லீவுக்கும் சம்பந்தம் இருக்குது🤤👌\n Sunday என்றால் விடுமுறை தானே இப்போ விடுமுறை எல்லாமே 'Sun'day தானே🤣!",
    "குளவி கொட்டினா வலிக்குது😳\nதேள் கொட்டினா வலிக்குது🙄\nதேனீ கொட்டினா வலிக்குது😒\nமுடி கொட்டினா வலிக்கலியே🤔😂!",
    "விக்கெட் விழுந்தால் விக்கெட் கீப்பர் சிரிக்க லாம்😂!\nஆனா கோல் விழுந்தால் கோல் கீப்பர் சிரிக்க முடியுமா🙄😂?",
    "புள்ளிமானுக்கு உடம்பெல்லாம் புள்ளி இருக்கும், ஆனால் கண்ணுக் குட்டிக்கு உடம்பு பூரா கண்ணு இருக்காது😂\nIthellam oru joke nu padikira unakku su*** irukkathu😂😂😂😂!",
    "மில்க் பிஸ்கட் மில்க்லே செஞ்சதுண்ணா டைகர் பிஸ்கட் டைகர்லே செஞ்சதா🤔🙄😂?",
    "தங்க செயினை உருக்கினா தங்கம் கிடைக்குது😅\nவெள்ளி செயினை உருக்கினா வெள்ளி கிடைக்குது😁\nசைக்கிள் செயினை உருக்கினா சைக்கிள் கிடைக்குமா😳🙄!",
    "என்னதான் புயல் காத்து வீசினாலும் சைக்கிளுக்கு பம்பு வைச்சு தான் காத்து அடிக்கணும்😂!\nAnd intha mokka joke ella kekura vana bat ah vaiche adikalum😂😂😂!",
    "பெரிய பேச்சாளரா இருந்தா எந்த ஸ்டேஜ்லே வேணா பேசலாம்😜\nஆனா கோமாஸ்டேஜ்லே பேசமுடியாது😂!",
    "தண்ணீரை தண்ணி என்று சொல்லலாம்🤷.\nஆனா கண்ணீரை கண்ணி என்று சொல்ல முடியுமா🤔😂?",
    "மீன் குழம்பிலே மீன் இருக்கும்😁,\nஅதுக் காக காரக் குழம்பிலே கார் இருக்கான்னு தேடலாமா😂😂!",
    "டூல்ஸ் பாக்ஸ்லே டூல்ஸ் பார்க்கலாம்😁\nஆனா மேட்ச் பாக்ஸ்லே மேட்ச் பார்க்க முடியுமா😂?",
    "சவுத் இண்டியாவில் 'நார்த்'தங்காய் கிடைக்கிறது🤔.\nஅதுபோல நார்த் இண்டியாவில் சவுத்தங்காய் கிடைக்குமா😂?",
    "சைக்கிள் போகும்போது அதோடு சைக்கிள் ஸ்டாண்ட் போகும்😊. ஆனால், பஸ் போகும் போது அதோடு பஸ் ஸ்டாண்ட் போகுமா😳😂?",
    "லஞ்ச் பேக்ல லஞ்ச் எடுத்துண்டு போறோம்.😕\nஅதுக்காக ஸ்கூல் பேக்ல ஸ்கூல் எடுத்துண்டு போக முடியுமா😂?",
    "மிளகாய்ப் பொடி வேண்டுமென்றால் மிளகாயை இடிக்கணும்.😁\n அதற்காக மூக்குப் போடி வேண்டுமென்றால் மூக்கை இடித்துக் கொள்ளாதே😂😂!",
 )

ABUSE_STRINGS = (
"Palla odachi kaila kuduthuruven🥱",
"Hair ah pudungu🤭",
"Po di dog🤣", 
"Railway station la suthuravan ella inga vandhurukane🤢",
"Vaaya moodu da korangu🤫",
"Nandri ketta naaye😡", 
"Manda bathiram", 
"Ennada ithu mooji🤣 Sethula mukkuna mathiri iruku🤣",
"Vayila nalla varuthu🤬 Ean thalaivan @THE_BOSS_OF_TELEGRAM kaga tha amaithiya iruke🥱", 
"Nenga moodetu irukalam nu computer solluthu sir😑",
"Yar da avan /abuse /abuse nu pottu uyira vanguran😒",
"Dai unaya na kutralathula pathene🤔 ovvoru trees ka thavi thavi pova🤭 unaku inga enna vela 🤣",
"Na unaya eppudi thitunalu unayala hair ah kooda pudunga mudiyathu🤣🤣🤣", 
"Moonja odaichi kaila koduthuruve pathuko🤫",
"Enga team no way kitta mothi par da mudinja🤣, unayala hair ah kooda pudunga mudiyathu🤭,only for haters😒", 
"Ivan evan da mutta paiyan🤢", "yenaya ethavathu un grp la add panni admin podu na soldre😒",
"Yar da ivan loosu mathiri olaruran", 
"Ivan yarrda pombala poruki ah irukan🥱",
"Po di anguttu🤬",
"Summa summa kadup hair ah eatha koodathu🤬",
"Ena sound vidura 🥱 Vaya odachiruve😡", 
"Enaku /abuse nu command pottavar periya mannar parambora🤢 Ivar yarayachu thitta sonan na thitaluma 🤣🥱",
"Dai ne ena avalo periya kinguh ah😡,Iru nalaki unaku sangu tha 🥱", "Ean area la nan than da raaja .👿", "Ippa ean da kadharura🤣", "Moonjum aalum mandayayum paaru🤣",
"Na enna unaku velakarana ne /abuse nu potta na soldrathuku😡", "Po da baadu🥱",
"Thambi enna pa unaku ippa prechana🙄",
"Enna da landha🥱",
"Sanda na sollu sirappa senjiruvom🥱", 
"Kuttralathula iruka vendiyavangala inga vandhu namma uyira vanguranga", 
"Po da kundu papa🤣🤭",
"Yar da enaya koopitathu🙄", 
"Po da uncle ooda wife🤣", 
"I am tired , ipa na yarayu thittura nalamai la illa pa 🥱",
"Kanna nondi eduthuruve 👀", "Seruppu keela iruku , innum oru sec la ne mela irupa🤣",
"Vanga grandma👵", "Po da panni.... Next rhyming ah na pesuna nee odeeruva🤣",
"Pongada nengalu unga /abuse um😒" 
    )

SING_STRINGS = (
"🎶 ஹே ரக்கிட் ரக்கிட் ரக்கிட்ட...", 
"🎶 என் கண்ணுகுள்ள ஒரு சிருக்கி கட்டிபுட்டாளே என்ன இருக்கி மனசகட்டி போட மறுத்தாளே ஹய்யோ, ஹய்யையோ... 🎶",
"🎶 உன் பேரே தெரியாது உன்னை கூப்பிட முடியாது நான் உனக்கோர் பேர் வைத்தேன் உனக்கே தெரியாது... 🎶", 
"🎶 உனக்கென்ன வேணும் சொல்லு உலகத்தை காட்டச் சொல்லு புது இடம் புது மேகம் தேடி போவோமே... 🎶", 
"🎶 காதல மறக்க நினைச்சு சிரிக்கிறேன் என் காதலி முகத்த நினைச்சு சிரிக்கிறேன் சோகத்தில் லைப்ப நினைச்சு சிரிக்கிறேன் நான் கோவத்த அடக்க முடியல சிரிக்கிறேன்... 🎶", 
"🎶 உன்ன நெனச்சு நெனச்சு உருகி போனேன் மெழுகா நெஞ்ச ஒதைச்சு ஒதைச்சு பறந்து போனா அழகா... 🎶",
"🎶 ஏதோ ஒன்று என்னை தாக்க யாரோ போல உன்னை பார்க்க... 🎶", 
"🎶 எதிர் வீட்டு ஹீரோயினி நீ லெமன் மின்ட்டு கூலர்மா நீ ஏதோ கொஞ்சம் கிளாமருதான் நீ அதுகின்னமா... 🎶",
"🎶எதுக்காக கிட்ட வந்தாளோ? எத தேடி விட்டு போனாளோ விழுந்தாலும் நா ஒடஞ்சே போயிருந்தாலும் உன் நினைவிருந்தாலே போதும் நிமிர்ந்திடுவேனே நானும்🎶", 
"🎶இங்கே இங்கே ஒரு மர்லின் மன்றோ நான்தான் உன்கையின் காம்பில் பூ நான் நம் காதல் யாவும் தேன்தான்\nபூவே பூவே நீ போதை கொள்ளும் பாடம் மனம் காற்றைப்போல ஓடும் உன்னை காதல் கண்கள் தேடும்🎶", 
"ஆண்: 🥰ஓ... மஞ்சள் குங்குமம் தாலியின் சிறப்பு பெண்களுக்கெல்லாம் இன்னொரு பொறப்பு🥰🥰\nபெண்: டும் டும் டும் டும்☺\nஆண்: டும் டும் டும் டுடும் டுடும் டும் டும் டும் டும்😁", 
"🎶மனசுல பூங்காத்து நீ பாக்கும் திசையில் வீசும் போது நமக்குன்னு ஒரு தேசம் அதில் இருவரும் சேர்ந்து ஒன்னா வாழ்வோம்🎶", 
"🎶சார பாம்பு சடை சலவை செஞ்ச இடை சாட்டா வீசும் நடை உனக்குதான்\nமார்பில் மச்சபடை மனசில் ரெட்டை கொட தோதா தூக்கும் இடம் உனக்குதான்\nஎன் கூச்சம் எல்லாம் குத்தகைக்கு உனக்குதான்\nஎன் கொழுகொழுப்பு இலவசம் உனக்குதான்🎶", 
"🎶hand la glass..glass la scotch eyes-u full-aa tear-u\nempty life-u.. girl-u come-u life reverse gear-u\nlovvu lovvu ..oh my lovvu you showed me bouv-u cow-u cow-u holi cow-u i want u hear now-u🎶", "🎶சின்னச் சின்ன ஆச, உள்ள திக்கித் திக்கிப் பேச! மல்லிகப்பூ வாசம், கொஞ்சம் காத்தோட வீச! உத்து உத்துப் பார்க்க,நெஞ்சில் முத்து முத்தா வேர்க்க! புத்தம் புது வாழ்க்க, என்ன உன்னோட சேர்க்க!🎶", "🎶Insta கிராமத்துல வாடி வாழலாம் நாம வாழும் நிமிஷத்தெல்லாம் சுட்டு தள்ளலாம்\nநானும் நீயும் சேரும் பொது தாறுமாறு தான் அந்த FaceBook-இல் பிச்சிக்கிடும் Like-உ Share-உ தான்🎶", 
"🎶ஏ மைக்ரோ மிடி போடட்டா பூனை நட நடக்கட்டா ஜோலிக்கே பீஜேன்னு சோக்கா பாடட்டா\nஏ இங்கிலீபீசு வேணான்டி இந்தி பீசு வேணான்டி கரகாட்டம் ஆடிக்கிட்டே தமிழில் பாடேன்டி🎶",
"🎶என் நாடியை சிலிர்க்க வைத்தாய் என் இரவெல்லாம் வெளிச்சம் தந்தாய்\nஎன் ஆண் கர்வம் மறந்தின்று உன் முன்னே பணிய வைத்தாய்🎶"
    )

GIFS = [
    "CgACAgQAAx0CSVUvGgAC7KpfWxMrgGyQs-GUUJgt-TSO8cOIDgACaAgAAlZD0VHT3Zynpr5nGxsE",
    "CgACAgUAAx0CU_rCTAABAjdgX1s4NVaeCls6YaH3p43vgdCRwQIAAqsAA4P_MFUYQhyoR-kgpRsE",
    "CgACAgUAAx0CU_rCTAABAjdSX1s3fq5iEJ64YeQLKI8cD7CSuSEAAlUBAAJu09hW5iqWB0hTPD4bBA",
]

SLAP_MASHA_TEMPLATES = (
    "Slap me one more time and I'll mute you.",
    "Stop slapping me. REEEEEEEEEEEEEE.",
    [
        "I am muting you for a minute.",  # normal reply
        "Stop slapping me just because I can't mute you. REEEEEEEEEE.",  # reply to admin
        "tmute",  # command
        "Shut up!",
        "Silence!",
    ],
)

SLAP_TEMPLATES = (
    "{user2} was killed by magic.",
    "{user2} starved without pats.",
    "{user2} was knocked into the void by {user1}.",
    "{user2} fainted.",
    "{user2} is out of usable Pokemon! {user2} whited out!.",
    "{user2} is out of usable Pokemon! {user2} blacked out!.",
    "{user2} got rekt.",
    "{user2}'s melon was split by {user1}.",
    "{user2} was sliced and diced by {user1}.",
    "{user2} played hot-potato with a grenade.",
    "{user2} was knifed by {user1}.",
    "{user2} ate a grenade.",
    "{user2} is what's for dinner!",
    "{user2} was terminated by {user1}.",
    "{user1} spammed {user2}'s email.",
    "{user1} RSA-encrypted {user2} and deleted the private key.",
    "{user1} put {user2} in the friendzone.",
    "{user1} slaps {user2} with a DMCA takedown request!",
    "{user2} got a house call from Doctor {user1}.",
    "{user1} beheaded {user2}.",
    "{user2} got stoned...by an angry mob.",
    "{user1} sued the pants off {user2}.",
    "{user2} was one-hit KO'd by {user1}.",
    "{user1} sent {user2} down the memory hole.",
    "{user2} was a mistake. - '{user1}' ",
    "{user2} was made redundant.",
    "{user1} {hits} {user2} with a bat!.",
    "{user1} {hits} {user2} with a Taijutsu Kick!.",
    "{user1} {hits} {user2} with X-Gloves!.",
    "{user1} {hits} {user2} with a Jet Punch!.",
    "{user1} {hits} {user2} with a Jet Pistol!.",
    "{user1} {hits} {user2} with a United States of Smash!.",
    "{user1} {hits} {user2} with a Detroit Smash!.",
    "{user1} {hits} {user2} with a Texas Smash!.",
    "{user1} {hits} {user2} with a California Smash!.",
    "{user1} {hits} {user2} with a New Hampshire Smash!.",
    "{user1} {hits} {user2} with a Missouri Smash!.",
    "{user1} {hits} {user2} with a Carolina Smash!.",
    "{user1} {hits} {user2} with a King Kong Gun!.",
    "{user1} {hits} {user2} with a baseball bat - metal one.!.",
    "*Serious punches {user2}*.",
    "*Normal punches {user2}*.",
    "*Consecutive Normal punches {user2}*.",
    "*Two Handed Consecutive Normal Punches {user2}*.",
    "*Ignores {user2} to let them die of embarassment*.",
    "*points at {user2}* What's with this sassy... lost child?.",
    "*Hits {user2} with a Fire Tornado*.",
    "{user1} pokes {user2} in the eye !",
    "{user1} pokes {user2} on the sides!",
    "{user1} pokes {user2}!",
    "{user1} pokes {user2} with a needle!",
    "{user1} pokes {user2} with a pen!",
    "{user1} pokes {user2} with a stun gun!",
    "{user2} is secretly a Furry!",
    "Hey Everybody! {user1} is asking me to be mean!",
    "( ･_･)ﾉ⌒●~* (･.･;) <-{user2}",
    "Take this {user2}\n(ﾉﾟДﾟ)ﾉ ))))●~* ",
    "Here {user2} hold this\n(｀・ω・)つ ●~＊",
    "( ・_・)ノΞ●~*  {user2}\nDieeeee!!.",
    "( ・∀・)ｒ鹵~<≪巛;ﾟДﾟ)ﾉ\n*Bug sprays {user2}*.",
    "( ﾟДﾟ)ﾉ占~<巛巛巛.\n-{user2} You pest!",
    "( う-´)づ︻╦̵̵̿╤── \(˚☐˚”)/ {user2}.",
    "{user1} {hits} {user2} with a {item}.",
    "{user1} {hits} {user2} in the face with a {item}.",
    "{user1} {hits} {user2} around a bit with a {item}.",
    "{user1} {throws} a {item} at {user2}.",
    "{user1} grabs a {item} and {throws} it at {user2}'s face.",
    "{user1} launches a {item} in {user2}'s general direction.",
    "{user1} starts slapping {user2} silly with a {item}.",
    "{user1} pins {user2} down and repeatedly {hits} them with a {item}.",
    "{user1} grabs up a {item} and {hits} {user2} with it.",
    "{user1} ties {user2} to a chair and {throws} a {item} at them.",
    "{user1} gave a friendly push to help {user2} learn to swim in lava.",
    "{user1} bullied {user2}.",
    "Nyaan ate {user2}'s leg. *nomnomnom*",
    "{user1} {throws} a master ball at {user2}, resistance is futile.",
    "{user1} hits {user2} with an action beam...bbbbbb (ง・ω・)ง ====*",
    "{user1} ara ara's {user2}.",
    "{user1} ora ora's {user2}.",
    "{user1} muda muda's {user2}.",
    "{user2} was turned into a Jojo reference!",
    "{user1} hits {user2} with {item}.",
    "Round 2!..Ready? .. FIGHT!!",
    "WhoPixel will oof {user2} to infinity and beyond.",
    "{user2} ate a bat and discovered a new disease.",
    "{user1} folded {user2} into a paper plane",
    "{user1} served {user2} some bat soup.",
    "{user2} was sent to his home, the planet of the apes.",
    "{user1} kicked {user2} out of a moving train.",
    "{user2} just killed John Wick’s dog.",
    "{user1} performed an Avada Kedavra spell on {user2}.",
    "{user1} subjected {user2} to a fiery furnace.",
    "Sakura Haruno just got more useful than {user2}",
    "{user1} unplugged {user2}'s life support.",
    "{user1} subscribed {user2}' to 5 years of bad internet.",
    "You know what’s worse than Dad jokes? {user2}!",
    "{user1} took all of {user2}'s cookies.",
    "{user2} wa mou.......Shindeiru! - {user1}.",
    "{user2} lost his race piece!",  # No game no life reference
    "Shut up {user2}, you are just {user2}.",  # No game no life reference
    "{user1} hits {user2} with Aka si anse!",  # No game no life reference
    "@NeoTheKitty scratches {user2}",  # Pixels pet cat - @NeoTheKitty
    "Majin buu ate {user2}",  # Dbz
    "Goblin slayer slays {user2}",  # Goblin Slayer
)

PAT_TEMPLATES = (
    "{user1} pats {user2} on the head.",
    "*gently rubs {user2}'s head*.",
    "*{user1} mofumofus {user2}'s head*",
    "*{user1} messes up {user2}'s head*",
    "*{user1} intensly rubs {user2}'s head*",
    "*{user2}'s waifu pats their head*",
    "*{user2}'s got free headpats*",
    "No pats for {user2}!",
    "Oh no! We are all out of pats.",
    "This is a designated no pat zone!",
    "No pats for {user2}!",
    "{user1} spoils {user2} with headpats!",
    "{user2} received one free headpat!",
    "{user1} headpats {user2} whilst giving a lap pillow",
    "{user1} aggressively pats {user2}",
    "{user1} gently strokes {user2}'s head",
    "Pat, pat, pat, pat",
    "{user2} could not escape {user1}'s headpats",
    "{user2}.exe has stopped working",
    "{user1} rubs {user2} on the neck",
    "Must... extort... HEADPATS",
    "{user1} headpats {user2}'s head with a pat",
    "{user1} pats {user2} unexpectedly",
    "{user1} pats {user2} with consent, maybe?",
    "Pat pat, {user2} honto kawaii ne!",
    "{user1} headpats {user2} at 420apm",
    "{user1} bellyrubs {user2}",
    "{user1} pats {user2} friendlily",
    "{user2} uses HEADPATS? O KAWAII KOTO",
    "*headpats.gif intensifies for {user2}*",
    "(*´ω´(*｀ω｀)",
    "(ｏ・_・)ノ”(ᴗ_ ᴗ。)",
    "(*￣▽￣)ノ”(- -*)",
    "(っ´ω`)ﾉ(╥ω╥)",
    "( ´Д｀)ﾉ(´･ω･`) ﾅﾃﾞﾅﾃﾞ",
)

PAT_GIFS = (
    "CgACAgQAAxkBAALRX19Xs7tBdOH1gQwS_rglVRkTbgVYAAKEAgACmQn9UWlyGa_xy9_aGwQ",
    "CgACAgEAAxkBAALRYF9Xs8EnhsDfDpld3ILoqTbzDmwxAAJFAAOJxjlHECanwn69E5QbBA",
)

PAT_STICKERS = (
    "CAACAgQAAxkBAALRWV9Xs4HH0XaXfhZe-jWaZoXfs-IsAAJYAwACdDgSEHYOt4KvL02oGwQ",
    "CAACAgQAAxkBAALRXF9Xs6XmIeDbnoL1wiDky0TdX-CvAAKKAQAC1TMzC9A3CtiT2rqVGwQ",
)

PING_STRING = (
    "PONG!!",
    "I am here!",
)

ITEMS = (
    "cast iron skillet",
    "angry meow",
    "cricket bat",
    "wooden cane",
    "shovel",
    "toaster",
    "book",
    "laptop",
    "rubber chicken",
    "spiked bat",
    "heavy rock",
    "chunk of dirt",
    "ton of bricks",
    "rasengan",
    "spirit bomb",
    "100-Type Guanyin Bodhisattva",
    "rasenshuriken",
    "Murasame",
    "ban",
    "chunchunmaru",
    "Kubikiribōchō",
    "rasengan",
    "spherical flying kat",
)

THROW = (
    "throws",
    "flings",
    "chucks",
    "hurls",
)

HIT = (
    "hits",
    "whacks",
    "slaps",
    "smacks",
    "bashes",
    "pats",
)

EYES = [
    ["⌐■", "■"],
    [" ͠°", " °"],
    ["⇀", "↼"],
    ["´• ", " •`"],
    ["´", "`"],
    ["`", "´"],
    ["ó", "ò"],
    ["ò", "ó"],
    ["⸌", "⸍"],
    [">", "<"],
    ["Ƹ̵̡", "Ʒ"],
    ["ᗒ", "ᗕ"],
    ["⟃", "⟄"],
    ["⪧", "⪦"],
    ["⪦", "⪧"],
    ["⪩", "⪨"],
    ["⪨", "⪩"],
    ["⪰", "⪯"],
    ["⫑", "⫒"],
    ["⨴", "⨵"],
    ["⩿", "⪀"],
    ["⩾", "⩽"],
    ["⩺", "⩹"],
    ["⩹", "⩺"],
    ["◥▶", "◀◤"],
    ["◍", "◎"],
    ["/͠-", "┐͡-\\"],
    ["⌣", "⌣”"],
    [" ͡⎚", " ͡⎚"],
    ["≋"],
    ["૦ઁ"],
    ["  ͯ"],
    ["  ͌"],
    ["ළ"],
    ["◉"],
    ["☉"],
    ["・"],
    ["▰"],
    ["ᵔ"],
    [" ﾟ"],
    ["□"],
    ["☼"],
    ["*"],
    ["`"],
    ["⚆"],
    ["⊜"],
    [">"],
    ["❍"],
    ["￣"],
    ["─"],
    ["✿"],
    ["•"],
    ["T"],
    ["^"],
    ["ⱺ"],
    ["@"],
    ["ȍ"],
    ["  "],
    ["  "],
    ["x"],
    ["-"],
    ["$"],
    ["Ȍ"],
    ["ʘ"],
    ["Ꝋ"],
    [""],
    ["⸟"],
    ["๏"],
    ["ⴲ"],
    ["◕"],
    ["◔"],
    ["✧"],
    ["■"],
    ["♥"],
    [" ͡°"],
    ["¬"],
    [" º "],
    ["⨶"],
    ["⨱"],
    ["⏓"],
    ["⏒"],
    ["⍜"],
    ["⍤"],
    ["ᚖ"],
    ["ᴗ"],
    ["ಠ"],
    ["σ"],
    ["☯"],
]

MOUTHS = [
    ["v"],
    ["ᴥ"],
    ["ᗝ"],
    ["Ѡ"],
    ["ᗜ"],
    ["Ꮂ"],
    ["ᨓ"],
    ["ᨎ"],
    ["ヮ"],
    ["╭͜ʖ╮"],
    [" ͟ل͜"],
    [" ͜ʖ"],
    [" ͟ʖ"],
    [" ʖ̯"],
    ["ω"],
    [" ³"],
    [" ε "],
    ["﹏"],
    ["□"],
    ["ل͜"],
    ["‿"],
    ["╭╮"],
    ["‿‿"],
    ["▾"],
    ["‸"],
    ["Д"],
    ["∀"],
    ["!"],
    ["人"],
    ["."],
    ["ロ"],
    ["_"],
    ["෴"],
    ["ѽ"],
    ["ഌ"],
    ["⏠"],
    ["⏏"],
    ["⍊"],
    ["⍘"],
    ["ツ"],
    ["益"],
    ["╭∩╮"],
    ["Ĺ̯"],
    ["◡"],
    [" ͜つ"],
]

EARS = [
    ["q", "p"],
    ["ʢ", "ʡ"],
    ["⸮", "?"],
    ["ʕ", "ʔ"],
    ["ᖗ", "ᖘ"],
    ["ᕦ", "ᕥ"],
    ["ᕦ(", ")ᕥ"],
    ["ᕙ(", ")ᕗ"],
    ["ᘳ", "ᘰ"],
    ["ᕮ", "ᕭ"],
    ["ᕳ", "ᕲ"],
    ["(", ")"],
    ["[", "]"],
    ["¯\\_", "_/¯"],
    ["୧", "୨"],
    ["୨", "୧"],
    ["⤜(", ")⤏"],
    ["☞", "☞"],
    ["ᑫ", "ᑷ"],
    ["ᑴ", "ᑷ"],
    ["ヽ(", ")ﾉ"],
    ["\\(", ")/"],
    ["乁(", ")ㄏ"],
    ["└[", "]┘"],
    ["(づ", ")づ"],
    ["(ง", ")ง"],
    ["⎝", "⎠"],
    ["ლ(", "ლ)"],
    ["ᕕ(", ")ᕗ"],
    ["(∩", ")⊃━☆ﾟ.*"],
]

TOSS = ("Heads", "Tails")

EIGHTBALL = [
    "🟢 As I see it, yes.",
    "🟡 Ask again later.",
    "🟡 Better not tell you now.",
    "🟡 Cannot predict now.",
    "🟡 Concentrate and ask again.",
    "🟡 Don’t count on it.",
    "🟢 It is certain.",
    "🟢 It is decidedly so.",
    "🟢 Most likely.",
    "🔴 My reply is no.",
    "🔴 My sources say no.",
    "🔴 Outlook not so good.",
    "🟢 Outlook good.",
    "🟡 Reply hazy, try again.",
    "🟢 Signs point to yes.",
    "🔴 Very doubtful.",
    "🟢 Without a doubt.",
    "🟢 Yes.",
    "🟢 Yes – definitely.",
    "🟢 You may rely on it.",
]

DECIDE = ("Yes.", "No.", "Maybe.")

TABLE = (
    "(╯°□°）╯彡 ┻━┻",
    "I ran out of tables, will order more.",
    "Go do some work instead of flippin tables.",
)
